version: "3.8"

services:
  db:
    image: postgres
    container_name: poc_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=poc_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: poc_backend
    ports:
      - 3000:3000
    volumes:
      - .:/user/app
    links:
      - db
    depends_on:
      - db
volumes:
  pgdata:
